algoritmo "Contador"
var
   contador, valor, salto : inteiro
inicio
      contador <-0
      escreva("insira um valor a ser contado : ")
      leia(valor)
      escreva("Qual o valr do salto?: ")
      leia(salto)
      enquanto (contador <= valor) faca
               escreval(contador)
               contador <- contador + salto
      fimEnquanto
      escreval(" Fim Do contador")
      
fimalgoritmo